### ISSUE TITLE
Is there something strange in openMM/Gromacs outputs from CHARMM gui? Is this revelant for us?

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NmrLipidsCholXray#11]
It is suggested in connection with another discussion that there would be something wrong in openMM or Gromacs outputs from CHARMM gui: https://github.com/NMRLipids/NmrLipidsCholXray/issues/9#issuecomment-255077334

The discussion can be continued here.

**Comment by jmelcr** [comment]
This probably requires further clarification, please, see the above [comment](https://github.com/NMRLipids/NmrLipidsCholXray/issues/9#issuecomment-255077334) first before continuing.

The comment tries to convince that Charmm-gui generated parameters are not the same for all simulation engines (Gromacs and openMM tested) and that there are most probably some errors in the conversions from format to format ("lost in translation") - or something else. 
The reason for that is that charmm-gui takes the Charmm36 parameter set from somewhere (let's assume it is flawless) and in one of the last step of the input generator it provides you input files in a format suitable for various simulation engines, e.g. Gromacs, openMM, Charmm, NAMD. 
Let's assume that the simulation engines are comparably accurate so that when you feed them with parameters A, you get result A in all of them. 
This is for example true for openMM and Gromacs - when I used Gromacs format of input files, I obtained matching results from the two engines (as in the mentioned [comment](https://github.com/NMRLipids/NmrLipidsCholXray/issues/9#issuecomment-255077334)).
However, when I used the parameter set in the format suitable for openMM, I got a slightly different result.
As a consequence I conclude that the parameter set A (Gromacs format) is different from parameter set B (openMM format) which makes charmm-gui unreliable source of such input data.

Hope it's clearer now. 

Luckily for us, the error in the DOPs is comparable with the classical force field accuracy, so I believe that the data based on charmm-gui parameters can be still used for some analysis, one only has to bear in mind the possibility of some glitches. 
The trend is also maintained, the cholesterol effect only looks a bit larger with parameter set A, the Gromacs file format.

**Comment by jmelcr** [comment]
I performed rather a bit systematic study on the reliability of simulation engines and parameter sources concentrating on the above discussed Charmm36 model from
- Charmm-gui
- MacKerell website

using simulation engines
- Gromacs 5
- openMM 7

The deuterium order parameter differences between the combinations looked more prominent at simulations with high cholesterol concentrations, hence I show here results with POPC:Cholesterol 50:50 mixture. 
Conclusions from the DOP plots:
- charmm-gui based simulations are separate from the rest and do not even agree with one another (Gromacs,blue X openMM,green)
- MacKerell based simulations agree beautifully well when the settings, especially the VdW switch is the same (Gromacs,violet & openMM,orange)
- different form of the VdW switch sligthly varies the results (openMM,red)
- use of heavy Hydrogens and 4 fs time step doesn't change the result (not shown)
![dops_all_sims_comparison_sn1](https://cloud.githubusercontent.com/assets/12782348/21314958/17b33fa2-c5fa-11e6-9a6d-00c90c5e5ec2.png)
![dops_all_sims_comparison_sn2](https://cloud.githubusercontent.com/assets/12782348/21314960/1cc68aee-c5fa-11e6-9b86-267d56234deb.png)

Now I hope it is clear that simulation software are of comparable accuracy, and for charmm36 model, charmm-gui is good for initial conditions, not for reliable parameters - especially in a project, where we intend to look at rather tiny differences in the DOPs.

**Comment by jmelcr** [comment]
The new simulations are at:

1. 50% cholesterol
- [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.209080.svg)](https://doi.org/10.5281/zenodo.209080) openMM
- [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.209070.svg)](https://doi.org/10.5281/zenodo.209070) openMM (Gromacs format parameters)

2. 30% cholesterol
- [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.209360.svg)](https://doi.org/10.5281/zenodo.209360) openMM
- [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.209362.svg)](https://doi.org/10.5281/zenodo.209362) Gromacs
- [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.209381.svg)](https://doi.org/10.5281/zenodo.209381) openMM (Gromacs format parameters)

3. 0% cholesterol
- [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.209391.svg)](https://doi.org/10.5281/zenodo.209391) openMM  (Gromacs format parameters)

**Comment by ohsOllila** [comment]
Ok, it seems to me now that there is indeed something strange in Charmm-gui outputs. Have you been or planning to be in contact with Charmm-gui developers? It might be a good idea to calculate also 
some differences in area per molecule for that. This might more intuitive parameter for some people.

**Comment by jmelcr** [comment]
I think it is convincing now, so I'll wrap it up and send it to Charmm-gui developers.
APL will be useful too, yes.

**Comment by TomPiggot** [comment]
Hi,

I'm not completely convinced by this.

Looking at the results from the pure POPC simulations I did before (https://github.com/NMRLipids/NmrLipidsCholXray/issues/4), the simulations were performed using either the CHARMM-GUI GROMACS files (for the simulations using Josef's starting structure), or with force field files from the MacKerell website (the sims using my starting structure). From the order parameters, I cannot see any differences between force field parameters within these pure POPC simulations (I've included an order parameter plot here for just one of hydrogens to save people having to look through all the numbers of the order parameters reported before).

![popc_op_c36_diff_ff_params](https://cloud.githubusercontent.com/assets/21039047/21858256/57ae39f8-d820-11e6-9591-855992ec9376.png)

Josef, are your results just from one simulation using each setting? If so, my concern is that these results would potentially not be reproducible.

To definitely say if there are differences in force field parameters from different sources, surely all that needs to be done is to calculate single point energies without cut-off's and see if they match? Happy to do this for different GROMACS version of the CHARMM36 lipid parameters/force field if that would be useful? In particular I can check my original conversion (which I tested before and they match the standard CHARMM force field parameters; see Tables S1 and S2 in http://pubs.acs.org/doi/suppl/10.1021/ct3003157), the MacKerell website force field and the force field provided by the CHARMM-GUI.

Cheers

Tom

**Comment by TomPiggot** [comment]
I should also say that these previous results of mine obviously don't compare GROMACS and OpenMM, so I cannot say much about possible differences with the OpenMM CHARMM-GUI outputs. 

Calculating the same single-point energies in OpenMM (i.e. with the same structure) would be the easy way to check the OpenMM CHARMM-GUI outputs. I've never used OpenMM so I'd have to leave this to someone else.

**Comment by jmelcr** [comment]
It's nice to see that the results match at least in some cases.

**Comment by ohsOllila** [comment]
It seems to me that jmelcr has reported problems in systems with cholesterol, while TomPiggot has problem free system without cholesterol. Maybe the issue is in the cholesterol parameters?

I agree with TomPiggot that single-point energies should be definitely calculated for this kind of checks.

**Comment by jmelcr** [comment]
I wrote to the Charmm-gui developers through their web-interface with no response, so I don't know whether they are only to do something about it....

**Comment by ohsOllila** [comment]
The potential issue with CHARMM-GUI is hopefully fixed already by now. I will close this issue.
