### ISSUE TITLE
Can the overestimation of order parameters in CHARMM36 and Slipid simulations with cholesterol be explained by missing undulations?

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NmrLipidsCholXray#16]

**Comment by mattijavanainen** [comment]
Doesn't seem to be the case. I ran bilayers with 800 and 1800 POPC (in addition to the older data with 200 POPC) using Charmm36, and the results are mutually identical (last 80 ns of 100 ns simulations analysed). Simulation data are here: https://doi.org/10.5281/zenodo.545941

[order-size.pdf](https://github.com/NMRLipids/NmrLipidsCholXray/files/919090/order-size.pdf)

**Comment by AlexHdeVriesMDGroup** [comment]
My short answer to the blog question: “Can the overestimation of order parameters in CHARMM36 and Slipid simulations with cholesterol be explained by missing undulations?” is: “Most likely it cannot.” 

I have looked at segmental order parameters for the Martini coarse-grained model for lipids to come to this conclusion. I should stress that the statement holds for SMALL SINGLE BILAYER PATCHES in comparison to LARGE MULTILAMELLAR STACKS. I have attached slides from a presentation, including some personal comments. I hope to publish this in the open literature some day, but cannot give a reasonable estimate for when. I have discussed with Samuli and Markus and they were enthousiastic and this post is the result of their encouragements. 

Alex H. de Vries, Molecular Dynamics Group, University of Groningen, The Netherlands

[UndulationsAndOrderParameters-forNMRLIPIDS.pdf](https://github.com/NMRLipids/NmrLipidsCholXray/files/948880/UndulationsAndOrderParameters-forNMRLIPIDS.pdf)

From the comments to the slides, a slightly more elaborate conclusion and discussion: The Martini DPPC system at full hydration shows that segmental order parameters should be scaled by a factor 0.99, i.e. they would be 1% too high in a small simulated patch compared to a multilamellar stack. This is probably less than the uncertainty in the experimental data and than the statistical errors in the simulation data. 

What are the ifs and buts? Martini is not atomistic, segments are not C-D vectors. In general, the Martini model reproduces area per lipid and lipid thickness well, also bending modulus and area compressibility are the right order of magnitude. The scaling between local and overall normal should not be that different. The relation between C-D order parameters and C-C segmental order parameters is -2 (i.e. SCD = -SCC/2, assuming tetrahedral carbons and negligible small contributions from D-C-D vibrational motions), and so the 1% holds there as well. Undulations depend on the nature of the lipid and the hydration level, and so the scaling should in principle be investigated for different systems. Unsaturated lipids (POPC vs DPPC) lead to larger bending moduli than saturated ones, increasing undulations; on the other hand, cholesterol condenses the bilayer, reducing fluctuations (I am not sure about the full hydration level, but I do not expect it to be higher than that of pure DPPC, and so that would not increase undulations). It would be interesting to explore some other systems with Martini and I might come around to doing it…

Perhaps the most important criticism in relation to the current NMRlipids project is, that the project focuses on the HEADGROUP order parameters, and here only the tail segments are analyzed. Of course I can analyze the other Martini segments as well, but I suspect their relation to the C-D vectors in the headgroup region is much less straightforward than for the tails…

**Comment by ohsOllila** [comment]
Thanks to @mattijavanainen and @AlexHdeVriesMDGroup for highly useful information. The conclusion seems to be quite clearly that undulations do not make significant to the order parameters. I am busy with other things (again), but I will progress including this information in the manuscript asap.

**Comment by ohsOllila** [comment]
This is now resolved in Fig. S2 in the supplementary information of the NMRlipids databank manuscript (https://doi.org/10.26434/chemrxiv-2023-jrpwm-v2) shown below. In line with results reported by @mattijavanainen and @AlexHdeVriesMDGroup above, order parameters and form factor minina (zeros) do not depend on box size (undulations). However, form factor lobe heights do depend. I will close this issue now.

![image](https://user-images.githubusercontent.com/7114769/236414711-3a47c724-9a9b-4b13-9eb7-8a8482380dcb.png)
