### ISSUE TITLE
How to use the scripts

### ISSUE THREAD

**Issue by ffavelar** [NMRLipids/NmrLipidsCholXray#6]
Could anyone please tell me how to use the scripts to obtain the form factors?

Thanks in advance.

**Comment by ohsOllila** [comment]
I did reopen this because the documentation does not exist and it should be done.

I am currently collecting the data in the MATCH repository. The data in Data folder, mapping files in MAPPING folder. In README.md files in each data set are the commands that needs to be run before makereport.sh, for example see https://github.com/NMRLipids/MATCH/tree/master/Data/Lipid_Bilayers/POPC%2B50%25chol/T310K/MODEL_CHARMM36_GROMACS5.0

I have not had time to make a documentation about this yet, sorry about that. Hopefully this helps. Do not hesitate to ask further questions.

**Comment by ohsOllila** [comment]
This concerns the preliminary databank and is therefore outdated. I will close this now.
