### ISSUE TITLE
Weird results for sn-2 chain order parameters from http://dx.doi.org/10.5281/zenodo.61649

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NmrLipidsCholXray#9]
As already mentioned in another issue (https://github.com/NMRLipids/NmrLipidsCholXray/issues/4#issuecomment-250431166), the pure POPC CHARMM36 data from [http://dx.doi.org/10.5281/zenodo.61649](http://dx.doi.org/10.5281/zenodo.61649) gives weird results for sn-2 chain order parameters.

The most characteristic feature are the large numbers for C2. 

I have now analyzed also the other data sets from [http://dx.doi.org/10.5281/zenodo.61649](http://dx.doi.org/10.5281/zenodo.61649) and they all had this feature. However, the data from [http://doi.org/10.5281/zenodo.61992](http://doi.org/10.5281/zenodo.61992) seems not to have this problem. For example, see https://github.com/NMRLipids/NmrLipidsCholXray/blob/master/FIGS/OrderParametersCHOL-eps-converted-to.pdf.

Also glycerol backbone order parameters (https://github.com/NMRLipids/MATCH/blob/master/Data/Lipid_Bilayers/POPC/T310K/MODEL_CHARMM36/Headgroup_Glycerol_Order_Parameters_Simulation.dat) from pure POPC from [http://dx.doi.org/10.5281/zenodo.61649](http://dx.doi.org/10.5281/zenodo.61649) are quite different than the results from the data used in NMRlipids I (https://github.com/NMRLipids/MATCH/blob/master/Data/Lipid_Bilayers/POPC/T303K/MODEL_CHARMM36_GROMACS4.5/Headgroup_Glycerol_Order_Parameters_Simulation.dat) which were in much better agreement with experiments.

@mattijavanainen
Can you recall some difference in preparing the systems between [http://dx.doi.org/10.5281/zenodo.61649](http://dx.doi.org/10.5281/zenodo.61649) and [http://doi.org/10.5281/zenodo.61992](http://doi.org/10.5281/zenodo.61992) ? According to the description both are from CHARMM GUI.

**Comment by mattijavanainen** [comment]
Samuli realized that there was a bug in the charmm36.itp file provided by CHARMM-GUI version 1.7*. Systems with 0–30% cholesterol were run with an older (i.e. buggy) version of the topology, while systems with 40–50% were run with a newer one. I'm now rerunning the 0% system with the newer topology to see if this is the reason behind the non-matching results. I'll hope to get the results tomorrow.

*) http://www.charmm-gui.org/?doc=log

**Comment by jmelcr** [comment]
Hope it also explains the difference between my new charmm-gui based simulations and the referenced [Matti's simulations](https://doi.org/10.5281/zenodo.61649)

DOPs:
![larger_older_matti--smaller_newer_joe_popc-30chl_compar](https://cloud.githubusercontent.com/assets/12782348/19113970/461bd7b0-8b0c-11e6-908b-0bcfc1cda89c.png)

erratum:
my chol conc is 33.3%, whereas Matti's 30% - was too quick in just doing it...

**Comment by mattijavanainen** [comment]
I'll rerun this system (chol 30%) as well with the correct itp.

**Comment by mattijavanainen** [comment]
Well, it seems that the weird behavior is indeed due to the bad itp provided by charmm-gui. I'll rerun the systems simulated with the bad itp (0,10,20, and 30%) and upload the data to zenodo soon.

**Comment by mattijavanainen** [comment]
The systems that are re-simulated with the correct .itp are here:
https://doi.org/10.5281/zenodo.159759

**Comment by ohsOllila** [comment]
The new simulations seems to fix the issue, see the figure with the new data: https://github.com/NMRLipids/NmrLipidsCholXray/blob/master/FIGS/OrderParametersPROGRAMS-eps-converted-to.pdf

**Comment by jmelcr** [comment]
I'll bring up openMM+GMX results for a correct POPC+30%Chol mixture soon.

**Comment by jmelcr** [comment]
70% POPC + 30% Cholesterol (right this time)
Parameters obtained from Charmm-gui v1.8
Gromacs 5.1.2 
openMM 7.0.1
both Cuda

DOPs from Gromacs are still a bit more "rigid" than those from openMM.
I'll yet check APL and elongate the sims would it differ greatly (suggesting possible non-convergence)

Interestingly enough, DOPs agreed well between openMM and Gromacs (same versions) for pure POPC (issue #4).

![popc70-chol30_sn-1_omm7-gmx512_compar](https://cloud.githubusercontent.com/assets/12782348/19410457/50b1eaa0-92ed-11e6-9395-ebe35017ee3a.png)
![popc70-chol30_sn-2_omm7-gmx512_compar](https://cloud.githubusercontent.com/assets/12782348/19410459/553cd09e-92ed-11e6-9634-9cbe8adf3a99.png)

**Comment by jmelcr** [comment]
status update:
openMM can read some of Gromacs files directly - which is what I did and I'm currently double-checking the above result with an extra simulation that uses openMM7 as simulation engine, but uses charmm-gui generated parameter set originally meant for the use with GMX. 
- running simulations also for 50% cholesterol conc. (GMX and openMM)

**Comment by jmelcr** [comment]
## Charmm-gui generated topologies and parameters are unreliable.

I ran several simulations of 84POPC+36Chol molecules (i.e. 30%Chol) forming a bilayer to make this point:
- Gromacs 5.1.2 with Gromacs topologies and parameters
- openMM 7 with openMM topologies and parameters
- openMM 7 with Gromacs topologies and parameters (same as used with Gromacs simulation)
  All topologies and parameters were generated by [Charmm-gui membrane builder](http://charmm-gui.org/?doc=input/membrane)

The point was to see which of the discussed concerns is more likely:
- Gromacs simulation engine provides wrong results with Charmm36 model
- charmm36 parameters given by Charmm-gui are incorrect (at least those in Gromacs format)

Because I already saw a split in results generated by Gromacs+gmx_parms vs. openMM+openMM_parms, I tested what openMM+Gromacs_parms would generate:
1. openMM result -> Gromacs is wrong
2. Gromacs result -> parameters for Gromacs are wrong
3. something else -> ???

It had happened that it is the second case - charmm-gui generated parameters are inconsistent between openMM and Gromacs and, hence, unreliable. OpenMM simulation with the same parameters as used in Gromacs simulation gives same result as the Gromacs simulation. 
Which parameters are wrong? I didn't dig in (and don't really want to). 
Remedy? Use Charmm36 parameters from [MacKerell webpage])http://mackerell.umaryland.edu/charmm_ff.shtml#gromacs).

See the Order Parameters for sn-1 and sn-2 chains below:

![popc70-chol30_sn-1_omm7-gmx512_compar](https://cloud.githubusercontent.com/assets/12782348/19557451/05fafd94-96c6-11e6-9daf-faab10850d8b.png)
![popc70-chol30_sn-2_omm7-gmx512_compar](https://cloud.githubusercontent.com/assets/12782348/19557450/05f8e220-96c6-11e6-9d22-1ea542c1cf42.png)

**Comment by ohsOllila** [comment]
I do not understand how you can conclude based on this that the parameters for Gromacs are wrong? It seems equally or more likely to me that there is something weird in the openMM results.

This discussion should be actually moved elsewhere (new issue or https://github.com/NMRLipids/NmrLipidsCholXray/issues/4). This issue is actually solved. I also consider https://github.com/NMRLipids/NmrLipidsCholXray/issues/4 practically solved. This is something else. 

EDIT: Now I opened an issue for the potential further discussion: https://github.com/NMRLipids/NmrLipidsCholXray/issues/11

**Comment by ohsOllila** [comment]
I close this issue because this https://github.com/NMRLipids/NmrLipidsCholXray/issues/9#issuecomment-251511157 turned out to be the reason for the original problem. The discussion about other topics should be continued elsewhere.

**Comment by jmelcr** [comment]
> I do not understand how you can conclude based on this that the parameters for Gromacs are wrong?

Gromacs is OK. I show that the Charmm-gui generated input files for Gromacs are inconsistent with the input files meant for openMM suggesting they are wrong in some way.
I made a larger comment in the issue #11
